urls.py
from django.conf.urls import url

from . import views

app_name = 'reports'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<pk>[0-9]+)/asn/$', views.ASNDetail.as_view(), name='asnDetail'),
    url(r'^monitoredAsn/$', views.ASNList.as_view(), name='asnList'),
    url(r'^data/congestion/$', views.congestionData, name='congestionData'),
    url(r'^data/forwarding/$', views.forwardingData, name='forwardingData'),
]

models.py
from django.db import models

class ASN(models.Model):
    number = models.IntegerField(primary_key=True)
    name   = models.CharField(max_length=255)

    def __str__(self):
        return "ASN%s %s" % (self.number, self.name)

class Congestion(models.Model):
    timebin = models.DateTimeField(db_index=True)
    asn = models.ForeignKey(ASN, on_delete=models.CASCADE)
    magnitude = models.FloatField(default=0.0)
    deviation = models.FloatField(default=0.0)
    # TODO add a table for tfidf results
    label     = models.CharField(max_length=255)

    def __str__(self):
        return "%s AS%s" % (self.timebin, self.asn.number)
    

class Forwarding(models.Model):
    timebin = models.DateTimeField(db_index=True)
    asn = models.ForeignKey(ASN, on_delete=models.CASCADE)
    magnitude = models.FloatField(default=0.0)
    absoluteResp = models.FloatField(default=0.0)
    # TODO add a table for tfidf results
    label     = models.CharField(max_length=255, default="")

    def __str__(self):
        return "%s AS%s" % (self.timebin, self.asn.number)

class CongestionRanking(models.Model):
    asn = models.ForeignKey(ASN, on_delete=models.CASCADE)
    score = models.FloatField(default=0.0)
    timebin = models.DateTimeField()

    def __str__(self):
        return "%s AS%s" % (self.timebin, self.asn.number)


class ForwardingRanking(models.Model):
    asn = models.ForeignKey(ASN, on_delete=models.CASCADE)
    score = models.FloatField(default=0.0)
    timebin = models.DateTimeField()

    def __str__(self):
        return "%s AS%s" % (self.timebin, self.asn.number)

views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.core import serializers
from django.db.models import Avg, When, Sum, Case, FloatField

from datetime import datetime, date, timedelta
import json

from .models import ASN, Congestion, Forwarding

class DateTimeEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, datetime):
            # return o.isoformat()
            return o.strftime("%Y-%m-%d %H:%M:%S")

        return json.JSONEncoder.default(self, o)

def index(request):
    monitoredAsn = ASN.objects.order_by("number")

    today = date.today()
    if "today" in request.GET:
        part = request.GET["today"].split("-")
        today = date(int(part[0]), int(part[1]), int(part[2]))
    limitDate = today-timedelta(days=7)
    print(limitDate)
    # TODO remove the following line (used only with test data)
    limitDate = datetime(2015,1,1)

    topCongestion = ASN.objects.filter(congestion__timebin__gt=limitDate).annotate(score=Sum("congestion__magnitude")).order_by("-score")[:5]

    print(topCongestion)
    ulLen = 5
    if len(monitoredAsn)<15:
        ulLen = 2 #len(monitoredAsn)/3

    context = {"monitoredAsn0": monitoredAsn[:ulLen], "monitoredAsn1": monitoredAsn[ulLen:ulLen*2],
            "monitoredAsn2": monitoredAsn[ulLen*2:ulLen*3],"nbMonitoredAsn": len(monitoredAsn)-ulLen*3,
            "topCongestion": topCongestion }
    return render(request, "reports/index.html", context)

def search(request):
    req = request.GET["asn"]
    reqNumber = -1 
    try:
        if req.startswith("asn"):
            reqNumber = int(req[3:].partition(" ")[0]) 
        elif req.startswith("as"):
            reqNumber = int(req[2:].partition(" ")[0]) 
        else:
            reqNumber = int(req.partition(" ")[0])
    except ValueError:
        return HttpResponseRedirect(reverse("reports:index"))
    
    asn = get_object_or_404(ASN, number=reqNumber)
    return HttpResponseRedirect(reverse("reports:asnDetail", args=(asn.number,)))

def congestionData(request):
    asn = get_object_or_404(ASN, number=request.GET["asn"])
    data = Congestion.objects.filter(asn=asn.number)
    formatedData = {
            "x": list(data.values_list("timebin", flat=True)),
            "y": list(data.values_list("magnitude", flat=True))
            }
    return JsonResponse(formatedData, encoder=DateTimeEncoder) 

def forwardingData(request):
    asn = get_object_or_404(ASN, number=request.GET["asn"])
    data = Forwarding.objects.filter(asn=asn.number) 
    formatedData = {
            "x": list(data.values_list("timebin", flat=True)),
            "y": list(data.values_list("magnitude", flat=True))
            }
    return JsonResponse(formatedData, encoder=DateTimeEncoder) 


class ASNDetail(generic.DetailView):
    model = ASN
    # template_name = "reports/asn_detail.html"


class ASNList(generic.ListView):
    model = ASN
    # template_name = "reports/asn_detail.html"

templates/reports/asn_detail.html
{% extends "reports/base_reports.html" %}

{% block head %}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}


{% block body %}

<div class="row">
    <div class="col-12">
        <h1>AS{{ asn.number }} {{ asn.name }}</h1> 
    </div>
    <div class="col-12">
        <h2>Congestion Level</h2>
        <div id="plotCongestion" ></div>
    </div>
        
    <div class="col-12">
        <h2>Forwarding Anomalies</h2>
        <div id="plotForwarding"></div>
        <script>
            function makeplot() {
                Plotly.d3.json("{% url "reports:congestionData" %}?asn={{ asn.number }}", function(data){ makePlotly(data, "plotCongestion", "Congestion level") } );
                Plotly.d3.json("{% url "reports:forwardingData" %}?asn={{ asn.number }}", function(data){ makePlotly(data, "plotForwarding", "Forwarding anomalies") } );

            };

            function makePlotly( data, divId, title ){
                var plotDiv = document.getElementById(divId);
                var traces = [{
                    x: data["x"],
                    y: data["y"]
                }];

                Plotly.newPlot(divId, traces,
                    {title: title});
            };
            makeplot();
        </script>
    </div>
        
</div>

{% endblock %}

templates/reports/asn_list.html
{% extends "reports/base_reports.html" %}


{% block body %}

<div class="row">
    <div class="col-12">
        <h1>{{ object_list|length }} Monitored ASes</h1> 
    </div>
    <div class="col-6">
        <ul>
        {% for asn in object_list %}
        <li><a href="{% url "reports:asnDetail" asn.number %}">AS{{ asn.number }} {{ asn.name }}</a></li>
        {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

templates/reports/base.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="{% static "reports/apple-touch-icon.png" %}">

        <link rel="stylesheet" href="{% static "reports/css/bootstrap.min.css" %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static "reports/css/bootstrap-theme.min.css" %}">
        <link rel="stylesheet" href="{% static "reports/css/main.css" %}">

        <script src="{% static "reports/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js" %}"></script>
        {% block head %}{% endblock %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url "reports:index" %}">Internet Weather Report</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <form class="navbar-form navbar-right" role="form" action="{% url "reports:search" %}" method="get">
            <div class="form-group">
              <input type="text" placeholder="Enter an ASN" class="form-control" name="asn">
            </div>
            <button type="submit" class="btn btn-success glyphicon glyphicon-search"></button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      {% block body %}
      {% endblock %}

      <hr>

    </div> <!-- /container -->        
    
    <footer class="container-fluid footer" >
    <div class="row">
        <div class="col-md-0 col-lg-3 col-xs-0"></div>
        <div class="col-md-4 col-lg-2 col-xs-4">
            <dl>
            <dt>Browse</dt>
            <dd><a href="{% url "reports:index" %}">Last Reports</a></dd>
            <dd><a href="{% url "reports:asnList" %}">Monitored ASes</a></dd>
            </dl>
        </div>
        <div class="col-md-4 col-lg-2 col-xs-4">
            <dl>
            <dt>Documentation</dt>
            <dd><a href="">How it works?</a></dd>
            <dd><a href="">API</a></dd>
            </dl>
        </div>
        <div class="col-md-4 col-lg-2 col-xs-4">
            <dl>
            <dt><a href="">Contact us</a></dt>
            </dl>
        </div>
        <div class="col-md-0 col-lg-3 col-xs-0"></div>
    </div>
    </footer>    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{% static "reports/js/vendor/jquery-1.11.2.min.js" %}><\/script>')</script>

        <script src="{% static "reports/js/vendor/bootstrap.min.js" %}"></script>

        <script src="{% static "reports/js/main.js" %}"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>

templates/reports/base_reports.html
{% extends "reports/base.html" %}

templates/reports/index.html
{% extends "reports/base_reports.html" %}

{% block head %}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block errorMessage %}{% endblock %}

{% block body %}
<div class="row">
    
    <h2>Top ASes reported in the last 7 days</h2>
    <div class="col-lg-12">
        <div id="plotCongestion"></div>
    
    </div>
    <div class="col-md-3"></div>
    <div class="col-md-9">
    </div>
    <h2>See other ASes</h2> 
    <div class="col-md-3">
        <ul>
        {% for asn in monitoredAsn0 %}
        <li><a href="{% url "reports:asnDetail" asn.number %}">AS{{ asn.number }} {{ asn.name }}</a></li>
        {% endfor %}
        </ul>
    </div>
    <div class="col-md-3">
        <ul>
        {% for asn in monitoredAsn1 %}
        <li><a href="{% url "reports:asnDetail" asn.number %}">AS{{ asn.number }} {{ asn.name }}</a></li>
        {% endfor %}
        </ul>
    </div>
    <div class="col-md-3">
        <ul>
        {% for asn in monitoredAsn2 %}
        <li><a href="{% url "reports:asnDetail" asn.number %}">AS{{ asn.number }} {{ asn.name }}</a></li>
        {% endfor %}
        and <a href="{% url "reports:asnList" %}" >{{ nbMonitoredAsn }} more...</a>
        </ul>
    </div>
</div>
<script>
    function makeplot() {
        Plotly.newPlot("plotCongestion", []);
        {% for asn in topCongestion %}
        Plotly.d3.json("{% url "reports:congestionData" %}?asn={{ asn.number }}", function(data){ addPlotly(data, "plotCongestion", "AS{{ asn.number }}") } );
        {% endfor %}
    };

    function addPlotly( data, divId, label ){
        var plotDiv = document.getElementById(divId);
        var traces = [{
            x: data["x"],
            y: data["y"],
            name: label
        }];

        Plotly.addTraces(divId, traces);
    };
    makeplot();
</script>
{% endblock %}